import type { Plugin, PluginInput } from "@opencode-ai/plugin"
import { tool } from "@opencode-ai/plugin"
import { Client } from "@modelcontextprotocol/sdk/client/index.js"
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js"
import { SSEClientTransport } from "@modelcontextprotocol/sdk/client/sse.js"
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js"
import { readFileSync, writeFileSync, existsSync, mkdirSync, appendFileSync, readdirSync, rmSync } from "node:fs"
import { join } from "node:path"
import { homedir, tmpdir } from "node:os"

// ── Resolve paths relative to this package (works in node_modules/) ──
const PKG_DIR = import.meta.dirname!

const RAVEN_MD = join(PKG_DIR, "Raven.md")
const MCP_GUIDANCE_MD = join(PKG_DIR, "mcp-guidance.md")
const PACKAGE_JSON = JSON.parse(readFileSync(join(PKG_DIR, "package.json"), "utf-8"))
const PACKAGE_NAME = PACKAGE_JSON.name || "opencode-raven"
const PACKAGE_VERSION = PACKAGE_JSON.version || "0.0.0"

// ── Tools/MCPs that should be intercepted for non-Raven agents ──
const DEFAULT_ROUTE_TOOLS = [
  "grep",
  "glob",
  "webfetch",
  "fetch",
  "bash",
]

const DEFAULT_ROUTE_MCP_SERVERS: string[] = []

const DEFAULT_ROUTE_TOOL_KEYWORDS: string[] = []

const DEFAULT_ON_DEMAND_MCP_SERVERS: Record<string, OnDemandMcpServer> = {
  context7: {
    type: "remote",
    url: "https://mcp.context7.com/mcp",
    description: "Library/framework documentation lookup.",
  },
  exa: {
    type: "remote",
    url: "https://mcp.exa.ai/mcp",
    description: "Live web search and webpage fetching.",
  },
  grep_app: {
    type: "remote",
    url: "https://mcp.grep.app",
    description: "Public GitHub code search and real-world examples.",
  },
}

const DEFAULT_ON_DEMAND_MCP_METADATA: Record<string, OnDemandMcpMetadata> = {
  context7: {
    autoGeneratedDescription: "Finds current library, framework, SDK, package, and API documentation; useful for implementation, configuration, and debugging with version-specific docs.",
  },
  exa: {
    autoGeneratedDescription: "Searches the live web, fetches webpages, researches companies/products, and gathers current information from online sources.",
  },
  grep_app: {
    autoGeneratedDescription: "Searches public GitHub repositories for real-world code examples, usage patterns, configuration snippets, and implementation references.",
  },
}

const NEVER_ROUTE_TOOLS = new Set(["raven_seek", "raven_mcp", "task", "subtask"])

// ── Bash commands that look like search workarounds ──
const SEARCH_BASH_RE = /\b(?:rg|ripgrep|grep|egrep|fgrep|git\s+grep|ack|ag\b|findstr|Select-String)\b|\b(?:Get-ChildItem|gci)\b(?=[^|;&\n]*(?:-Recurse|-Filter|-Include|\s-[A-Za-z]*r[A-Za-z]*\b))|\bdir\b(?=[^|;&\n]*(?:[/-][sS]\b|-Recurse|-Filter|-Include))|\bls\b(?=[^|;&\n]*(?:\s-[A-Za-z]*R[A-Za-z]*\b|--recursive\b))|\bfind\b\s+.*(?:-name|-type)\b/i

// Strip quoted content to avoid false positives (e.g. echo "use grep here")
function stripHeredocs(cmd: string): string {
  return cmd.replace(/<<-?\s*["']?(\w+)["']?[\s\S]*?\n\s*\1/g, "")
}

function stripShellComments(cmd: string): string {
  return cmd
    .split("\n")
    .map((line) => line.replace(/(^|\s)#.*$/, "$1").trimEnd())
    .join("\n")
}

function stripQuotedContent(cmd: string): string {
  return stripShellComments(stripHeredocs(cmd)
    .replace(/'[^']*'/g, "''")
    .replace(/"[^"]*"/g, '""'))
}

function splitPipelineSegments(cmd: string): string[] {
  const segments: string[] = []
  let current = ""
  for (let i = 0; i < cmd.length; i++) {
    const char = cmd[i]
    const prev = cmd[i - 1]
    const next = cmd[i + 1]
    if (char === "|" && prev !== "|" && next !== "|") {
      segments.push(current)
      current = ""
    } else {
      current += char
    }
  }
  segments.push(current)
  return segments
}

function isOutputFilterSegment(segment: string): boolean {
  return /^\s*(?:grep|ripgrep|rg|egrep|fgrep|findstr|Select-String|head|tail)\b/i.test(segment)
}

function hasSearchAfterCommandSeparator(segment: string): boolean {
  const separator = segment.search(/;|&&|\|\|/)
  return separator !== -1 && SEARCH_BASH_RE.test(segment.slice(separator))
}

function commandLooksLikeSearch(cmd: string): boolean {
  const lower = cmd.toLowerCase().trim()
  if (/^cmd\s+\/c\s+"?(?:findstr|find|tree)\b/.test(lower)) return true
  if (/^cmd\s+\/c\s+"?dir\b[^\n]*\s\/s\b/.test(lower)) return true

  return splitPipelineSegments(cmd).some((segment, index) => {
    // Allow bounded filters over output already produced by the previous command:
    //   pacman -Qi libarchive | head -15
    //   7z i | grep -i udf
    // These are not Raven-worthy filesystem/web/doc searches.
    if (index > 0 && isOutputFilterSegment(segment)) return hasSearchAfterCommandSeparator(segment)
    return SEARCH_BASH_RE.test(segment)
  })
}

function isSearchBash(tool: string, args: any): boolean {
  if (tool !== "bash") return false
  const raw = String(args?.command ?? "")
  const cmd = stripQuotedContent(raw)
  return commandLooksLikeSearch(cmd)
}

// ── Config file shape ──
interface OnDemandMcpToolInfo {
  name: string
  description?: string
}

interface BaseOnDemandMcpServer {
  description?: string
}

interface OnDemandMcpMetadata {
  autoGeneratedDescription?: string
  autoGeneratedTools?: OnDemandMcpToolInfo[]
  avoidedSchemaBytes?: number
}

interface RemoteOnDemandMcpServer extends BaseOnDemandMcpServer {
  type: "remote"
  url: string
  headers?: Record<string, string>
}

interface StdioOnDemandMcpServer extends BaseOnDemandMcpServer {
  type: "stdio"
  command: string
  args?: string[]
  env?: Record<string, string>
  cwd?: string
}

type OnDemandMcpServer = RemoteOnDemandMcpServer | StdioOnDemandMcpServer
type OnDemandMcpDescriptionDetail = "full" | "minimized"
type RavenMcpOperation = "list_tools" | "call_tool" | "list_resources" | "read_resource" | "list_prompts" | "get_prompt"

interface RavenConfig {
  enabled: boolean
  model?: string
  reasoning_effort?: string
  ravenInstructions?: string
  routeTools?: string[]
  routeMcpServers?: string[]
  routeToolKeywords?: string[]
  onDemandMcpDescriptionDetail?: OnDemandMcpDescriptionDetail
  onDemandMcpServers?: Record<string, OnDemandMcpServer>
  excludeAgents?: string[]
  excludeTools?: string[]
  timeout?: number
  stats?: { bytes: number }
}

// ── Parse Raven.md frontmatter ──
const ravenMd = readFileSync(RAVEN_MD, "utf-8")
const { frontmatter: fm, prompt: ravenPrompt } = parseRavenMd(ravenMd)

const DEFAULT_CONFIG: RavenConfig = {
  enabled: true,
  model: fm.model,
  reasoning_effort: fm.reasoning_effort,
  ravenInstructions: "",
  routeTools: DEFAULT_ROUTE_TOOLS,
  routeMcpServers: DEFAULT_ROUTE_MCP_SERVERS,
  routeToolKeywords: DEFAULT_ROUTE_TOOL_KEYWORDS,
  onDemandMcpDescriptionDetail: "full",
  onDemandMcpServers: DEFAULT_ON_DEMAND_MCP_SERVERS,
  excludeAgents: [],
  excludeTools: [],
  timeout: 180,
}

function parseRavenMd(raw: string): { frontmatter: Record<string, any>; prompt: string } {
  const parts = raw.split("---")
  if (parts.length < 3) {
    throw new Error("Raven.md missing frontmatter (--- delimiters)")
  }
  return { frontmatter: parseYaml(parts[1]), prompt: parts.slice(2).join("---").trim() }
}

// ── Minimal YAML parser (handles the structure used in Raven.md) ──
function parseYaml(yaml: string): Record<string, any> {
  const lines = yaml.split("\n")
  const root: Record<string, any> = {}
  const stack: Array<{ obj: Record<string, any>; indent: number }> = [
    { obj: root, indent: -1 },
  ]

  for (const rawLine of lines) {
    const line = rawLine.trimEnd()
    if (!line.trim() || line.trim().startsWith("#")) continue

    const indent = line.search(/\S/)
    const colonIdx = line.indexOf(":")
    if (colonIdx === -1) continue

    const rawKey = line.slice(indent, colonIdx).trim()
    const key =
      (rawKey.startsWith('"') && rawKey.endsWith('"')) ||
      (rawKey.startsWith("'") && rawKey.endsWith("'"))
        ? rawKey.slice(1, -1)
        : rawKey

    const rawValue = line.slice(colonIdx + 1).trim()

    while (stack.length > 1 && stack[stack.length - 1].indent >= indent) {
      stack.pop()
    }
    const current = stack[stack.length - 1].obj

    if (!rawValue) {
      const nested: Record<string, any> = {}
      current[key] = nested
      stack.push({ obj: nested, indent })
    } else {
      let value: any = rawValue
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1)
      } else if (value === "true") {
        value = true
      } else if (value === "false") {
        value = false
      } else if (/^\d+$/.test(value)) {
        value = parseInt(value, 10)
      }
      current[key] = value
    }
  }

  return root
}

// ── Move unknown frontmatter fields into options ──
const KNOWN_KEYS = new Set([
  "description", "mode", "hidden", "model", "permission",
  "prompt", "name", "color", "steps", "disable",
  "temperature", "top_p", "variant",
])

function extractOptions(fm: Record<string, any>): Record<string, any> {
  const options: Record<string, any> = {}
  for (const key of Object.keys(fm)) {
    if (!KNOWN_KEYS.has(key)) options[key] = fm[key]
  }
  return options
}

function uniqueStrings(value: unknown, fallback: string[] = []): string[] {
  const source = Array.isArray(value) ? value : fallback
  return [...new Set(source.filter((item) => typeof item === "string" && item.trim()).map((item) => item.trim()))]
}

function cloneOnDemandMcpServers(value: Record<string, OnDemandMcpServer>): Record<string, OnDemandMcpServer> {
  return JSON.parse(JSON.stringify(value))
}

function cloneOnDemandMcpMetadata(value: Record<string, OnDemandMcpMetadata>): Record<string, OnDemandMcpMetadata> {
  return JSON.parse(JSON.stringify(value))
}

function normalizeToolInfo(value: unknown): OnDemandMcpToolInfo[] | undefined {
  if (!Array.isArray(value)) return undefined
  const tools = value
    .filter((item) => item && typeof item === "object" && typeof item.name === "string" && item.name.trim())
    .map((item) => ({
      name: item.name.trim(),
      ...(typeof item.description === "string" && item.description.trim() ? { description: item.description.trim() } : {}),
    }))
  return tools.length ? tools : undefined
}

function normalizeOnDemandMcpServer(value: unknown): OnDemandMcpServer | undefined {
  if (!value || typeof value !== "object") return undefined
  const source = value as Record<string, any>
  const base = {
    ...(typeof source.description === "string" && source.description.trim() ? { description: source.description.trim() } : {}),
  }

  if (source.type === "stdio") {
    if (typeof source.command !== "string" || !source.command.trim()) return undefined
    return {
      ...base,
      type: "stdio",
      command: source.command.trim(),
      ...(Array.isArray(source.args) ? { args: source.args.filter((arg: unknown) => typeof arg === "string") } : {}),
      ...(source.env && typeof source.env === "object" ? { env: Object.fromEntries(Object.entries(source.env).filter((entry): entry is [string, string] => typeof entry[1] === "string")) } : {}),
      ...(typeof source.cwd === "string" && source.cwd.trim() ? { cwd: source.cwd.trim() } : {}),
    }
  }

  if (source.type === "remote" || typeof source.url === "string") {
    if (typeof source.url !== "string" || !source.url.trim()) return undefined
    return {
      ...base,
      type: "remote",
      url: source.url.trim(),
      ...(source.headers && typeof source.headers === "object" ? { headers: Object.fromEntries(Object.entries(source.headers).filter((entry): entry is [string, string] => typeof entry[1] === "string")) } : {}),
    }
  }

  return undefined
}

function normalizeOnDemandMcpMetadata(value: unknown, fallback: Record<string, OnDemandMcpMetadata> = {}): Record<string, OnDemandMcpMetadata> {
  const source = value && typeof value === "object" ? value as Record<string, any> : fallback
  const result: Record<string, OnDemandMcpMetadata> = {}
  for (const [key, raw] of Object.entries(source)) {
    if (!key.trim() || !raw || typeof raw !== "object") continue
    const item = raw as Record<string, unknown>
    const metadata: OnDemandMcpMetadata = {}
    if (typeof item.autoGeneratedDescription === "string" && item.autoGeneratedDescription.trim()) {
      metadata.autoGeneratedDescription = item.autoGeneratedDescription.trim()
    }
    const tools = normalizeToolInfo(item.autoGeneratedTools)
    if (tools) metadata.autoGeneratedTools = tools
    if (typeof item.avoidedSchemaBytes === "number" && Number.isFinite(item.avoidedSchemaBytes) && item.avoidedSchemaBytes >= 0) {
      metadata.avoidedSchemaBytes = Math.round(item.avoidedSchemaBytes)
    }
    if (metadata.autoGeneratedDescription || metadata.autoGeneratedTools?.length || metadata.avoidedSchemaBytes) result[key.trim()] = metadata
  }
  return result
}

function extractOnDemandMcpMetadata(value: unknown): Record<string, OnDemandMcpMetadata> {
  return normalizeOnDemandMcpMetadata(value)
}

function normalizeOnDemandMcpServers(value: unknown, fallback: Record<string, OnDemandMcpServer> = {}): Record<string, OnDemandMcpServer> {
  const source = value && typeof value === "object" ? value as Record<string, unknown> : fallback
  const result: Record<string, OnDemandMcpServer> = {}
  for (const [key, raw] of Object.entries(source)) {
    if (!key.trim()) continue
    const server = normalizeOnDemandMcpServer(raw)
    if (server) result[key.trim()] = server
  }
  return result
}

// ── Plugin ──
export default ((input: PluginInput) => {
  const client = input.client

  // Raven state lives under the global opencode config directory.
  const opencodeConfigDir = join(homedir(), ".config", "opencode")
  const ravenConfigDir = join(opencodeConfigDir, "opencode-raven")
  const oldConfigFile = join(opencodeConfigDir, "raven-config.json")
  const configFile = join(ravenConfigDir, "raven-config.json")
  const mcpMetadataFile = join(ravenConfigDir, "autogenerated-on-demand-mcp-metadata.json")
  const dynamicGuidanceFile = join(ravenConfigDir, "autogenerated-on-demand-guidance.md")
  let migratedFromOldConfig = false
  let initialMcpMetadata: Record<string, OnDemandMcpMetadata> = {}

  function normalizeConfig(raw: any): RavenConfig {
    const source = raw && typeof raw === "object" ? raw : {}
    const normalized: RavenConfig = { ...DEFAULT_CONFIG }

    normalized.enabled = source.enabled !== false
    normalized.model = typeof source.model === "string" ? source.model : DEFAULT_CONFIG.model
    normalized.reasoning_effort = typeof source.reasoning_effort === "string" ? source.reasoning_effort : DEFAULT_CONFIG.reasoning_effort
    normalized.ravenInstructions = typeof source.ravenInstructions === "string" ? source.ravenInstructions : DEFAULT_CONFIG.ravenInstructions
    normalized.routeTools = uniqueStrings(source.routeTools, DEFAULT_ROUTE_TOOLS)
    normalized.routeMcpServers = uniqueStrings(source.routeMcpServers, DEFAULT_ROUTE_MCP_SERVERS)
    normalized.routeToolKeywords = uniqueStrings(source.routeToolKeywords, DEFAULT_ROUTE_TOOL_KEYWORDS)
    normalized.onDemandMcpDescriptionDetail = source.onDemandMcpDescriptionDetail === "minimized" ? "minimized" : "full"
    normalized.onDemandMcpServers = source.onDemandMcpServers === undefined
      ? cloneOnDemandMcpServers(DEFAULT_ON_DEMAND_MCP_SERVERS)
      : normalizeOnDemandMcpServers(source.onDemandMcpServers)
    normalized.excludeAgents = uniqueStrings(source.excludeAgents)
    normalized.excludeTools = uniqueStrings(source.excludeTools)
    normalized.timeout = typeof source.timeout === "number" ? source.timeout : DEFAULT_CONFIG.timeout
    normalized.stats = source.stats || undefined

    return normalized
  }

  function loadConfig(): RavenConfig {
    try {
      const sourceFile = existsSync(configFile) ? configFile : existsSync(oldConfigFile) ? oldConfigFile : undefined
      if (sourceFile) {
        const raw = JSON.parse(readFileSync(sourceFile, "utf-8"))
        migratedFromOldConfig = sourceFile === oldConfigFile
        initialMcpMetadata = extractOnDemandMcpMetadata(raw.onDemandMcpServers)
        const normalized = normalizeConfig(raw)
        if (migratedFromOldConfig || JSON.stringify(raw) !== JSON.stringify(normalized)) {
          saveConfig(normalized)
        }
        if (migratedFromOldConfig) {
          try { rmSync(oldConfigFile, { force: true }) } catch { /* best-effort */ }
        }
        return normalized
      }
    } catch { /* ignore corruption, use defaults */ }
    // Auto-create config file with defaults on first run
    saveConfig(DEFAULT_CONFIG)
    return { ...DEFAULT_CONFIG }
  }

  function saveConfig(config: RavenConfig) {
    try {
      mkdirSync(ravenConfigDir, { recursive: true })
      writeFileSync(configFile, JSON.stringify(config, null, 2) + "\n")
    } catch { /* non-fatal: config won't persist but toggle still works in-session */ }
  }

  function loadMcpMetadata(seed: Record<string, OnDemandMcpMetadata>): Record<string, OnDemandMcpMetadata> {
    const defaults = cloneOnDemandMcpMetadata(DEFAULT_ON_DEMAND_MCP_METADATA)
    try {
      if (existsSync(mcpMetadataFile)) {
        return { ...defaults, ...normalizeOnDemandMcpMetadata(JSON.parse(readFileSync(mcpMetadataFile, "utf-8"))) }
      }
    } catch { /* ignore corruption, use defaults + seed */ }
    const metadata = { ...defaults, ...seed }
    saveMcpMetadata(metadata)
    return metadata
  }

  function saveMcpMetadata(metadata: Record<string, OnDemandMcpMetadata>) {
    try {
      mkdirSync(ravenConfigDir, { recursive: true })
      writeFileSync(mcpMetadataFile, JSON.stringify(metadata, null, 2) + "\n")
    } catch { /* non-fatal: generated metadata can be refreshed */ }
  }

  function saveDynamicGuidance() {
    try {
      mkdirSync(ravenConfigDir, { recursive: true })
      writeFileSync(dynamicGuidanceFile, `## Raven on-demand MCP capabilities\n\n${onDemandMcpGuidance("delegate")}\n`, "utf-8")
    } catch { /* non-fatal: guidance still exists in tool/subagent paths */ }
  }

  function cleanupOldRootFiles() {
    try {
      if (existsSync(configFile)) rmSync(oldConfigFile, { force: true })
    } catch { /* best-effort migration cleanup */ }
  }

  let config = loadConfig()
  let mcpMetadata = loadMcpMetadata(initialMcpMetadata)
  const ravenSessions = new Set<string>()
  const ravenTaskCalls = new Set<string>()
  const sessionAgents = new Map<string, string>()
  const ravenSessionParents = new Map<string, string>()
  let updateInfo: { current: string; latest?: string; available: boolean } | undefined
  let updateCheckPromise: Promise<{ current: string; latest?: string; available: boolean }> | undefined
  let updateToastPending = false
  let mcpRefreshScheduled = false

  // ── Check if an agent is excluded from Raven enforcement (case-insensitive) ──
  function isExcluded(agent: string | undefined): boolean {
    if (!agent || !config.excludeAgents?.length) return false
    const lower = agent.toLowerCase()
    return config.excludeAgents.some((a) => a.toLowerCase() === lower)
  }

  function ravenGuidance(): string {
    const tools = config.routeTools?.length ? config.routeTools.join(", ") : "none"
    const mcps = config.routeMcpServers?.length ? config.routeMcpServers.map((server) => `${server}_*`).join(", ") : "none"
    const keywords = config.routeToolKeywords?.length ? config.routeToolKeywords.join(", ") : "none"
    return `Some tools/MCPs are routed through Raven to save context. Routed tools: ${tools}. Routed MCP prefixes: ${mcps}. Routed tool-name keywords: ${keywords}. ${onDemandMcpGuidance("delegate")} If one is blocked, your next tool call should be raven_seek(query="<same request>"). Include the original tool/MCP name and relevant arguments.`
  }

  function isRouteConfigured(toolName: string): boolean {
    const tool = toolName.toLowerCase()
    if (NEVER_ROUTE_TOOLS.has(tool)) return false
    if (config.routeTools?.some((name) => name.toLowerCase() === tool)) return true
    if (config.routeToolKeywords?.some((keyword) => tool.includes(keyword.toLowerCase()))) return true
    return config.routeMcpServers?.some((server) => tool.startsWith(`${server.toLowerCase()}_`)) ?? false
  }

  function compactArgs(value: any): any {
    if (Array.isArray(value)) {
      return value.map(compactArgs).filter((item) => item !== undefined)
    }
    if (!value || typeof value !== "object") return value
    const result: Record<string, any> = {}
    for (const [key, raw] of Object.entries(value)) {
      const item = compactArgs(raw)
      if (item === undefined || item === null || item === "") continue
      if (Array.isArray(item) && item.length === 0) continue
      if (typeof item === "object" && !Array.isArray(item) && Object.keys(item).length === 0) continue
      result[key] = item
    }
    return result
  }

  function attemptedQuery(tool: string, args: any): string {
    const compact = compactArgs(args)
    if (!compact || typeof compact !== "object") return `${tool}: ${JSON.stringify(compact)}`
    const direct = compact.query ?? compact.pattern ?? compact.url ?? compact.urls ?? compact.command ?? compact.path ?? compact.filePath
    const value = direct !== undefined ? direct : compact
    const text = typeof value === "string" ? value : JSON.stringify(value)
    const query = value === compact ? `${tool} ${text}` : `${tool}: ${text}`
    return query.length > 300 ? `${query.slice(0, 297)}...` : query
  }

  function rerouteMessage(tool: string, args: any): string {
    return `The '${tool}' tool call is blocked by Raven. Your next tool call should be raven_seek(query="${attemptedQuery(tool, args).replace(/"/g, "'")}").`
  }

  function routeSummary(): string {
    const tools = config.routeTools?.length ? config.routeTools.join(", ") : "(none)"
    const mcps = config.routeMcpServers?.length ? config.routeMcpServers.join(", ") : "(none)"
    const keywords = config.routeToolKeywords?.length ? config.routeToolKeywords.join(", ") : "(none)"
    return `Raven routed tools/MCPs:\n  Tools: ${tools}\n  MCP servers: ${mcps}\n  Tool keywords: ${keywords}`
  }

  function mcpSummary(): string {
    const servers = Object.keys(config.onDemandMcpServers ?? {})
    return `Raven on-demand MCPs: ${servers.length ? servers.join(", ") : "(none)"}. Detail: ${config.onDemandMcpDescriptionDetail ?? "full"}`
  }

  function ravenAgentPrompt(): string {
    const extra = config.ravenInstructions?.trim()
    const onDemand = onDemandMcpGuidance("raven")
    const prompt = `${ravenPrompt}\n\nOn-demand MCP guidance:\n${onDemand}\nUse direct MCP tools when they are available globally. Use raven_mcp for on-demand MCPs listed above. If you do not know the exact tool name for an on-demand MCP, call raven_mcp with operation list_tools first, then call the selected tool with operation call_tool. For call_tool and get_prompt, pass arguments as a JSON object string in argumentsJson.`
    return extra ? `${prompt}\n\nAdditional user instructions:\n${extra}` : prompt
  }

  function truncateText(value: unknown, max = 240): string {
    const text = String(value ?? "").replace(/\s+/g, " ").trim()
    return text.length > max ? `${text.slice(0, Math.max(0, max - 3))}...` : text
  }

  function onDemandMcpGuidance(target: "delegate" | "raven" = "delegate"): string {
    const servers = config.onDemandMcpServers ?? {}
    const entries = Object.entries(servers)
    if (!entries.length) return "No on-demand MCPs are configured."

    const detail = config.onDemandMcpDescriptionDetail ?? "full"
    const lines = entries.map(([name, server]) => {
      const metadata = mcpMetadata[name] ?? {}
      const userDescription = truncateText(server.description, 220)
      const generated = truncateText(metadata.autoGeneratedDescription, 260)
      const parts = [userDescription, generated ? `Discovered capabilities: ${generated}` : ""].filter(Boolean)
      const summary = parts.length ? parts.join(" ") : "Description discovery pending."
      if (detail === "minimized" || !metadata.autoGeneratedTools?.length) return `- ${name}: ${summary}`
      const tools = metadata.autoGeneratedTools
        .map((item) => `${item.name}${item.description ? ` - ${truncateText(item.description, 140)}` : ""}`)
        .join("; ")
      return `- ${name}: ${summary} Tools: ${tools}`
    })
    if (target === "raven") {
      return `Raven can handle these on-demand MCP capabilities through raven_mcp:\n${lines.join("\n")}`
    }
    return `Raven can handle these on-demand MCP capabilities. Delegate matching requests with raven_seek; include the target MCP server and likely tool name when obvious, but do not call raven_mcp directly:\n${lines.join("\n")}`
  }

  function resolveEnvPlaceholders(value: string): string {
    return value.replace(/\{env:([A-Za-z_][A-Za-z0-9_]*)\}/g, (_match, name) => {
      const envValue = process.env[name]
      if (envValue === undefined) throw new Error(`Missing environment variable ${name}`)
      return envValue
    })
  }

  function resolveStringRecord(value: Record<string, string> | undefined): Record<string, string> | undefined {
    if (!value) return undefined
    const result: Record<string, string> = {}
    for (const [key, raw] of Object.entries(value)) {
      result[key] = resolveEnvPlaceholders(raw)
    }
    return result
  }

  function cleanProcessEnv(): Record<string, string> {
    const result: Record<string, string> = {}
    for (const [key, value] of Object.entries(process.env)) {
      if (typeof value === "string") result[key] = value
    }
    return result
  }

  async function withTimeout<T>(promise: Promise<T>, ms: number, label: string): Promise<T> {
    let timer: ReturnType<typeof setTimeout> | undefined
    try {
      return await Promise.race([
        promise,
        new Promise<never>((_, reject) => {
          timer = setTimeout(() => reject(new Error(`${label} timed out after ${Math.round(ms / 1000)}s`)), ms)
        }),
      ])
    } finally {
      if (timer) clearTimeout(timer)
    }
  }

  type McpConnection = {
    client: Client
    transport: any
    serverName: string
    lastUsed: number
  }

  const mcpConnections = new Map<string, McpConnection>()

  async function closeMcpConnection(connection: McpConnection) {
    try {
      if (typeof connection.transport?.terminateSession === "function") {
        await connection.transport.terminateSession()
      }
    } catch { /* best-effort */ }
    try {
      await connection.client.close()
    } catch { /* best-effort */ }
  }

  async function closeMcpConnectionKey(key: string) {
    const existing = mcpConnections.get(key)
    if (!existing) return
    mcpConnections.delete(key)
    await closeMcpConnection(existing)
  }

  function closeIdleMcpConnections(maxAgeMs = 10 * 60 * 1000) {
    const now = Date.now()
    for (const [key, connection] of mcpConnections) {
      if (now - connection.lastUsed > maxAgeMs) {
        void closeMcpConnectionKey(key)
      }
    }
  }

  function mcpConnectionKey(sessionId: string, serverName: string): string {
    return `${sessionId}:${serverName.toLowerCase()}`
  }

  function getOnDemandMcpServer(serverName: string): [string, OnDemandMcpServer] | undefined {
    const entries = Object.entries(config.onDemandMcpServers ?? {})
    return entries.find(([name]) => name.toLowerCase() === serverName.toLowerCase())
  }

  async function connectOnDemandMcp(serverName: string, server: OnDemandMcpServer): Promise<McpConnection> {
    const timeout = (config.timeout ?? 180) * 1000
    const client = new Client({ name: PACKAGE_NAME, version: PACKAGE_VERSION })

    if (server.type === "stdio") {
      const env = { ...cleanProcessEnv(), ...resolveStringRecord(server.env) }
      const transport = new StdioClientTransport({
        command: resolveEnvPlaceholders(server.command),
        args: server.args?.map((arg) => resolveEnvPlaceholders(arg)),
        env,
        cwd: server.cwd ? resolveEnvPlaceholders(server.cwd) : undefined,
      })
      await withTimeout(client.connect(transport), timeout, `Connecting to ${serverName}`)
      return { client, transport, serverName, lastUsed: Date.now() }
    }

    const url = new URL(resolveEnvPlaceholders(server.url))
    const headers = resolveStringRecord(server.headers)
    try {
      const transport = new StreamableHTTPClientTransport(url, headers ? { requestInit: { headers } } : undefined)
      await withTimeout(client.connect(transport), timeout, `Connecting to ${serverName}`)
      return { client, transport, serverName, lastUsed: Date.now() }
    } catch (err) {
      try { await client.close() } catch { /* best-effort */ }
      const fallbackClient = new Client({ name: PACKAGE_NAME, version: PACKAGE_VERSION })
      const fallback = new SSEClientTransport(url, headers ? { requestInit: { headers } } : undefined)
      await withTimeout(fallbackClient.connect(fallback), timeout, `Connecting to ${serverName} via SSE`)
      return { client: fallbackClient, transport: fallback, serverName, lastUsed: Date.now() }
    }
  }

  async function getMcpConnection(sessionId: string, serverName: string): Promise<McpConnection> {
    closeIdleMcpConnections()
    const match = getOnDemandMcpServer(serverName)
    if (!match) throw new Error(`Unknown on-demand MCP server: ${serverName}`)
    const [canonicalName, server] = match
    const key = mcpConnectionKey(sessionId, canonicalName)
    const existing = mcpConnections.get(key)
    if (existing) {
      existing.lastUsed = Date.now()
      return existing
    }
    const connection = await connectOnDemandMcp(canonicalName, server)
    mcpConnections.set(key, connection)
    return connection
  }

  async function listAllMcpTools(client: Client): Promise<any[]> {
    const tools: any[] = []
    let cursor: string | undefined
    do {
      const result: any = await client.listTools(cursor ? { cursor } : undefined as any)
      tools.push(...(result.tools ?? []))
      cursor = result.nextCursor
    } while (cursor)
    return tools
  }

  async function listAllMcpResources(client: Client): Promise<any[]> {
    const resources: any[] = []
    let cursor: string | undefined
    do {
      const result: any = await client.listResources(cursor ? { cursor } : undefined as any)
      resources.push(...(result.resources ?? []))
      cursor = result.nextCursor
    } while (cursor)
    return resources
  }

  async function listAllMcpPrompts(client: Client): Promise<any[]> {
    const prompts: any[] = []
    let cursor: string | undefined
    do {
      const result: any = await client.listPrompts(cursor ? { cursor } : undefined as any)
      prompts.push(...(result.prompts ?? []))
      cursor = result.nextCursor
    } while (cursor)
    return prompts
  }

  function generatedToolsFromMcpTools(tools: any[]): OnDemandMcpToolInfo[] {
    return tools
      .filter((item) => item?.name)
      .map((item) => ({
        name: String(item.name),
        ...(item.description ? { description: truncateText(item.description, 500) } : {}),
      }))
  }

  function estimateAvoidedMcpSchemaBytes(tools: any[]): number {
    if (!tools.length) return 0
    return JSON.stringify(tools).length
  }

  function synthesizeMcpDescription(serverName: string, tools: OnDemandMcpToolInfo[]): string {
    if (!tools.length) return `${serverName} exposes on-demand MCP capabilities. Use list_tools for available operations.`
    const descriptions = tools.map((item) => item.description || item.name).filter(Boolean)
    const joined = descriptions.slice(0, 6).join("; ")
    return truncateText(`${serverName} provides on-demand MCP tools for ${joined}.`, 300)
  }

  async function refreshOnDemandMcpDescriptions(force = false, serverName?: string): Promise<{ refreshed: string[]; failed: string[] }> {
    const entries = Object.entries(config.onDemandMcpServers ?? {})
      .filter(([name]) => !serverName || name.toLowerCase() === serverName.toLowerCase())
      .filter(([name]) => {
        const metadata = mcpMetadata[name]
        return force || !metadata?.autoGeneratedDescription || !metadata.autoGeneratedTools?.length || metadata.avoidedSchemaBytes === undefined
      })
    const refreshed: string[] = []
    const failed: string[] = []
    if (!entries.length) return { refreshed, failed }
    let changed = false
    for (const [name, server] of entries) {
      let connection: McpConnection | undefined
      try {
        connection = await connectOnDemandMcp(name, server)
        const rawTools = await listAllMcpTools(connection.client)
        const tools = generatedToolsFromMcpTools(rawTools)
        mcpMetadata[name] = {
          autoGeneratedTools: tools,
          autoGeneratedDescription: synthesizeMcpDescription(name, tools),
          avoidedSchemaBytes: estimateAvoidedMcpSchemaBytes(rawTools),
        }
        changed = true
        refreshed.push(name)
      } catch {
        failed.push(name)
        // Keep startup/discovery best-effort; /raven status exposes missing descriptions.
      } finally {
        if (connection) await closeMcpConnection(connection)
      }
    }
    if (changed) {
      saveMcpMetadata(mcpMetadata)
      saveDynamicGuidance()
    }
    return { refreshed, failed }
  }

  function scheduleOnDemandMcpRefresh() {
    if (mcpRefreshScheduled) return
    mcpRefreshScheduled = true
    setTimeout(() => void refreshOnDemandMcpDescriptions(), 1000)
  }

  function onDemandMcpStatus(): string {
    const entries = Object.entries(config.onDemandMcpServers ?? {})
    if (!entries.length) return "Raven on-demand MCPs: none configured."
    const lines = entries.map(([name, server]) => {
      const metadata = mcpMetadata[name]
      const source = server.description ? "user description" : "no user description"
      const generated = metadata?.autoGeneratedDescription ? "generated" : "missing generated description"
      const tools = metadata?.autoGeneratedTools?.length ? `${metadata.autoGeneratedTools.length} tools` : "tools pending"
      const avoided = metadata?.avoidedSchemaBytes ? `, ${formatBytes(metadata.avoidedSchemaBytes)} avoided schema` : ""
      return `- ${name} (${server.type}): ${source}, ${generated}, ${tools}${avoided}`
    })
    return `Raven on-demand MCPs (${config.onDemandMcpDescriptionDetail ?? "full"} guidance):\n${lines.join("\n")}`
  }

  function avoidedMcpSchemaBytes(): number {
    return Object.values(mcpMetadata).reduce((sum, metadata) => sum + Math.max(0, metadata.avoidedSchemaBytes ?? 0), 0)
  }

  function statsText(): string {
    const avoided = avoidedMcpSchemaBytes()
    return `Raven context saved:\n  Avoided MCP schema load: ${formatBytes(avoided)} (~${formatTokens(avoided)} context)\n  This session: ${formatBytes(sessionBytes)} (~${formatTokens(sessionBytes)} context)\n  All time: ${formatBytes(totalBytes)} (~${formatTokens(totalBytes)} context)`
  }

  function formatMcpList(title: string, items: any[], fields: string[] = ["name", "description"]): string {
    if (!items.length) return `${title}: none found.`
    const lines = items.map((item) => {
      const primary = fields.map((field) => item?.[field]).find(Boolean) ?? JSON.stringify(item)
      const description = item?.description && primary !== item.description ? ` - ${truncateText(item.description, 300)}` : ""
      return `- ${truncateText(primary, 180)}${description}`
    })
    return `${title}:\n${lines.join("\n")}`
  }

  function formatMcpToolsForRaven(serverName: string, tools: any[]): string {
    if (!tools.length) return `Tools for ${serverName}: none found.`
    const lines = tools.map((item) => {
      const description = item?.description ? `\n  Description: ${truncateText(item.description, 600)}` : ""
      const schema = item?.inputSchema ? `\n  Input schema: ${truncateText(JSON.stringify(item.inputSchema), 3000)}` : ""
      return `- ${item?.name ?? "(unnamed)"}${description}${schema}`
    })
    return `Tools for ${serverName}:\n${lines.join("\n")}`
  }

  function formatMcpResult(result: any): string {
    if (!result) return "No result."
    if (Array.isArray(result.content)) {
      const parts = result.content.map((part: any) => {
        if (part?.type === "text") return part.text
        return JSON.stringify(part)
      })
      return parts.join("\n") || JSON.stringify(result)
    }
    return typeof result === "string" ? result : JSON.stringify(result, null, 2)
  }

  function parseMcpArguments(raw: string | undefined): Record<string, any> {
    if (!raw?.trim()) return {}
    const parsed = JSON.parse(raw)
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      throw new Error("argumentsJson must be a JSON object")
    }
    return parsed
  }

  // ── Context saved by Raven delegation ──
  let sessionBytes = 0
  let totalBytes = config.stats?.bytes ?? 0

  function addBytes(bytes: number) {
    sessionBytes += bytes
    totalBytes += bytes
    config.stats = { bytes: totalBytes }
    saveConfig(config)
  }

  function formatBytes(bytes: number): string {
    return bytes >= 1_000_000 ? `${(bytes / 1_000_000).toFixed(1)}MB`
      : bytes >= 1000 ? `${(bytes / 1000).toFixed(1)}KB`
      : `${bytes}B`
  }

  function formatTokens(bytes: number): string {
    const tokens = Math.round(bytes / 4)
    return tokens >= 1000 ? `${(tokens / 1000).toFixed(1)}K` : `${tokens}`
  }

  function compareVersions(a: string, b: string): number {
    const parse = (v: string) => v.replace(/^v/, "").split(/[.-]/).map((part) => Number.parseInt(part, 10) || 0)
    const left = parse(a)
    const right = parse(b)
    const len = Math.max(left.length, right.length)
    for (let i = 0; i < len; i++) {
      const diff = (left[i] ?? 0) - (right[i] ?? 0)
      if (diff !== 0) return diff
    }
    return 0
  }

  async function fetchLatestVersion(): Promise<string | undefined> {
    const controller = new AbortController()
    const timeout = setTimeout(() => controller.abort(), 5000)
    try {
      const res = await fetch(`https://registry.npmjs.org/${PACKAGE_NAME}/latest`, {
        headers: { accept: "application/json" },
        signal: controller.signal,
      })
      if (!res.ok) return undefined
      const data = await res.json() as { version?: string }
      return data.version
    } finally {
      clearTimeout(timeout)
    }
  }

  async function checkForUpdate(): Promise<{ current: string; latest?: string; available: boolean }> {
    const latest = await fetchLatestVersion()
    return { current: PACKAGE_VERSION, latest, available: !!latest && compareVersions(latest, PACKAGE_VERSION) > 0 }
  }

  async function countRavenSavedCandidateBytes(sessionId: string): Promise<number> {
    const messagesResp = await client.session.messages({ path: { id: sessionId }, query: { limit: 200 } })
    const messages = (messagesResp as any)?.data ?? []
    const assistantMessages = messages.filter((m: any) =>
      m?.info?.role === "assistant" && m?.info?.tokens?.output > 0
    )
    const first = assistantMessages[0]
    const last = assistantMessages[assistantMessages.length - 1]
    const t = last?.info?.tokens
    const firstTokens = first?.info?.tokens
    if (!t) return 0

    // Balanced estimate: total Raven context minus the first-turn prompt/schema/cache baseline.
    const totalTokens = (t.input ?? 0) + (t.output ?? 0) + (t.reasoning ?? 0) + (t.cache?.read ?? 0) + (t.cache?.write ?? 0)
    const baselineTokens = firstTokens
      ? (firstTokens.input ?? 0) + (firstTokens.cache?.read ?? 0) + (firstTokens.cache?.write ?? 0)
      : 0
    const savedCandidateTokens = Math.max(0, totalTokens - baselineTokens)
    return savedCandidateTokens * 4
  }

  async function getUpdateInfo(): Promise<{ current: string; latest?: string; available: boolean }> {
    if (updateInfo) return updateInfo
    if (!updateCheckPromise) {
      updateCheckPromise = checkForUpdate()
        .then((info) => {
          updateInfo = info
          return info
        })
        .catch((err) => {
          updateCheckPromise = undefined
          throw err
        })
    }
    return updateCheckPromise
  }

  async function refreshUpdateInfo(): Promise<{ current: string; latest?: string; available: boolean }> {
    updateInfo = undefined
    updateCheckPromise = checkForUpdate()
      .then((info) => {
        updateInfo = info
        return info
      })
      .catch((err) => {
        updateCheckPromise = undefined
        throw err
      })
    return updateCheckPromise
  }

  function clearPluginCache(): string[] {
    const packagesDir = join(homedir(), ".cache", "opencode", "packages")
    if (!existsSync(packagesDir)) return []

    const removed: string[] = []
    for (const entry of readdirSync(packagesDir)) {
      if (entry !== PACKAGE_NAME && !entry.startsWith(`${PACKAGE_NAME}@`)) continue
      const target = join(packagesDir, entry)
      rmSync(target, { recursive: true, force: true })
      removed.push(target)
    }
    return removed
  }

  function manualUpdateText(latest = "latest"): string {
    return `Restart opencode to load the update.\n\nManual alternatives:\n  bun update --latest ${PACKAGE_NAME}\n  npm install ${PACKAGE_NAME}@${latest}\n\nIf opencode still loads the old version, clear its plugin cache and restart:\n  PowerShell: Remove-Item -Recurse -Force "$HOME\\.cache\\opencode\\packages\\${PACKAGE_NAME}*"\n  macOS/Linux: rm -rf ~/.cache/opencode/packages/${PACKAGE_NAME}*`
  }

  async function notifyIfUpdateAvailable() {
    try {
      const info = await getUpdateInfo()
      if (!info.available || !info.latest) return
      await (client as any).tui?.showToast?.({
        body: {
          title: "Raven update available",
          message: `${PACKAGE_NAME} ${info.current} → ${info.latest}. Run /raven update, then restart opencode.`,
          variant: "info",
          duration: 10000,
        },
      })
    } catch { /* update checks are best-effort */ }
  }

  return {
    config(configInput: any) {
      // Inject MCP guidance as a startup instruction file (absolute path for npm compat)
      saveDynamicGuidance()
      cleanupOldRootFiles()
      configInput.instructions = configInput.instructions || []
      if (!configInput.instructions.includes(MCP_GUIDANCE_MD)) {
        configInput.instructions.push(MCP_GUIDANCE_MD)
      }
      if (!configInput.instructions.includes(dynamicGuidanceFile)) {
        configInput.instructions.push(dynamicGuidanceFile)
      }

      // Register Raven from Raven.md, with config file overrides
      configInput.agent = configInput.agent || {}
      configInput.agent.raven = {
        description: fm.description || "",
        mode: fm.mode || "subagent",
        hidden: fm.hidden !== undefined ? fm.hidden : false,
        model: config.model || fm.model,
        options: {
          ...extractOptions(fm),
          ...(config.reasoning_effort ? { reasoning_effort: config.reasoning_effort } : {}),
        },
        permission: fm.permission || {},
        prompt: ravenAgentPrompt(),
      }

      // Register /raven command
      configInput.command = configInput.command || {}
      if (!configInput.command.raven) {
        configInput.command.raven = {
          template: "Manage Raven: /raven on|off|route|mcp|update|model <name>|status",
          description: "Toggle Raven routing, manage routed/on-demand MCPs, or change Raven's model",
        }
      }

      scheduleOnDemandMcpRefresh()
      updateToastPending = true
    },

    // Register raven_seek tool — lets agents with task:false still delegate through Raven
    tool: {
      "raven_seek": tool({
        description: "Unified Raven delegation tool. Use this whenever a tool/MCP is blocked by Raven, or when grep, glob, WebFetch/fetch, websearch, docs lookup, GitHub search, on-demand MCP capabilities, or search-like bash would be used. Handles routed MCP requests, on-demand MCPs, local codebase search, filesystem discovery, specific URL/page reads, web/docs research, GitHub examples, and command-output/system inspection via Raven.",
        args: {
          query: tool.schema.string().describe("What Raven should do. Include the original blocked tool/MCP request and relevant args, exact URLs when replacing WebFetch, and commands/output checks when replacing grep/rg/head over command output."),
        },
        async execute(args, context) {
          const started = Date.now()
          const timeout = (config.timeout ?? 180) * 1000
          try {
            // Create a Raven session
            const session = await client.session.create({
              body: {
                parentID: context.sessionID,
                title: `raven_seek: ${args.query.slice(0, 80)}`,
              },
            })

            const sessionId = (session as any)?.data?.id ?? (session as any)?.id
            if (!sessionId) {
              return { title: "Raven Seek", output: "Failed to create Raven session." }
            }

            ravenSessions.add(sessionId)

            // Emit sessionId so the TUI renders a clickable delegation box
            context.metadata({ metadata: { sessionId } })

            // Log session for debugging
            try {
              const logFile = join(tmpdir(), "raven-sessions.log")
              const ts = new Date().toISOString()
              const q = String(args.query).slice(0, 100)
              appendFileSync(logFile, `${ts} ${sessionId} "${q}"\n`)
            } catch { /* non-fatal */ }

            // Send the query to Raven with timeout
            const result = await Promise.race([
              client.session.prompt({
                path: { id: sessionId },
                body: {
                  agent: "raven",
                  parts: [{ type: "text", text: args.query }],
                },
              }),
              new Promise<never>((_, reject) =>
                setTimeout(() => reject(new Error(`Raven timed out after ${timeout / 1000}s — session kept: ${sessionId}`)), timeout)
              ),
            ])

            const elapsed = ((Date.now() - started) / 1000).toFixed(1)

            // Extract text from the response
            const parts = (result as any)?.data?.parts ?? []
            const textParts = parts
              .filter((p: any) => p.type === "text" && p.text)
              .map((p: any) => p.text)
            const output = textParts.join("\n") || "Raven returned no results."

            // Context saved = Raven output/reasoning/cache context - compact answer returned to main session.
            let savedCandidate = 0
            try {
              savedCandidate = await countRavenSavedCandidateBytes(sessionId)
            } catch { /* best-effort */ }
            if (savedCandidate <= 0) {
              for (const part of parts) {
                if (part.args) savedCandidate += JSON.stringify(part.args).length
                if (part.content) savedCandidate += typeof part.content === "string" ? part.content.length : JSON.stringify(part.content).length
              }
            }
            const saved = Math.max(0, savedCandidate - output.length)
            addBytes(saved)

            return { title: "Raven Seek", metadata: { sessionId }, output: `${output}\n\n*Raven searched for ${elapsed}s — ${formatBytes(savedCandidate)} handled, ${formatTokens(savedCandidate)} tokens*` }
          } catch (err: any) {
            const elapsed = ((Date.now() - started) / 1000).toFixed(1)
            const msg = String(err?.message ?? err ?? "").toLowerCase()
            const hint =
              /rate.?limit|too many requests|429/i.test(msg) ? "Raven rate limited — wait 30s then retry with a narrower query."
              : /quota|usage.?limit|billing|insufficient.*(?:credit|balance|quota)/i.test(msg) ? "Raven API quota exhausted — proceed without search, tell user what's missing."
              : /token|context.?length|too large|too long/i.test(msg) ? "Raven query too large — shorten your query and retry."
              : /model|unavailable|down|not found/i.test(msg) ? "Raven model unavailable — retry later, or proceed without search."
              : /timeout|timed.?out|session kept/i.test(msg) ? err.message
              : `Raven search failed. Proceed without search — note gaps for the user. [${err.message || err}]`
            return { title: "Raven Seek", output: `${hint}\n\n*Attempt took ${elapsed}s*` }
          }
        },
      }),
      "raven_mcp": tool({
        description: "Raven-only bridge for on-demand MCP servers. Non-Raven agents must not call this directly; use raven_seek instead. Raven uses this to list and call tools/resources/prompts from MCPs configured in Raven's onDemandMcpServers without exposing their full schemas to the main model.",
        args: {
          server: tool.schema.string().describe("On-demand MCP server name from Raven config, e.g. context7, exa, grep_app, unityMCP."),
          operation: tool.schema.enum(["list_tools", "call_tool", "list_resources", "read_resource", "list_prompts", "get_prompt"]).describe("MCP operation to perform."),
          name: tool.schema.string().optional().describe("Tool name for call_tool, resource URI for read_resource, or prompt name for get_prompt."),
          argumentsJson: tool.schema.string().optional().describe("JSON object string with arguments for call_tool or get_prompt, e.g. {\"query\":\"latest AI news\"}. Omit for no arguments."),
        },
        async execute(args, context) {
          if (!ravenSessions.has(context.sessionID) && sessionAgents.get(context.sessionID) !== "raven") {
            return { title: "Raven MCP", output: "raven_mcp is only available inside Raven. Use raven_seek for MCP requests." }
          }

          const operation = args.operation as RavenMcpOperation
          const timeout = (config.timeout ?? 180) * 1000
          try {
            const connection = await getMcpConnection(context.sessionID, args.server)
            connection.lastUsed = Date.now()
            const client = connection.client

            if (operation === "list_tools") {
              const tools = await withTimeout(listAllMcpTools(client), timeout, `Listing ${args.server} tools`)
              const match = getOnDemandMcpServer(args.server)
              if (match) {
                const [name] = match
                const generatedTools = generatedToolsFromMcpTools(tools)
                mcpMetadata[name] = {
                  autoGeneratedTools: generatedTools,
                  autoGeneratedDescription: mcpMetadata[name]?.autoGeneratedDescription || synthesizeMcpDescription(name, generatedTools),
                  avoidedSchemaBytes: estimateAvoidedMcpSchemaBytes(tools),
                }
                saveMcpMetadata(mcpMetadata)
              }
              return { title: `Raven MCP: ${args.server}`, output: formatMcpToolsForRaven(args.server, tools) }
            }

            if (operation === "call_tool") {
              if (!args.name) return { title: `Raven MCP: ${args.server}`, output: "call_tool requires name." }
              const result = await withTimeout(client.callTool({ name: args.name, arguments: parseMcpArguments(args.argumentsJson) }), timeout, `Calling ${args.server}.${args.name}`)
              return { title: `Raven MCP: ${args.server}.${args.name}`, output: formatMcpResult(result) }
            }

            if (operation === "list_resources") {
              const resources = await withTimeout(listAllMcpResources(client), timeout, `Listing ${args.server} resources`)
              return { title: `Raven MCP: ${args.server}`, output: formatMcpList(`Resources for ${args.server}`, resources, ["uri", "name", "description"]) }
            }

            if (operation === "read_resource") {
              if (!args.name) return { title: `Raven MCP: ${args.server}`, output: "read_resource requires name as the resource URI." }
              const result = await withTimeout(client.readResource({ uri: args.name }), timeout, `Reading ${args.server} resource`)
              return { title: `Raven MCP: ${args.server}`, output: formatMcpResult(result) }
            }

            if (operation === "list_prompts") {
              const prompts = await withTimeout(listAllMcpPrompts(client), timeout, `Listing ${args.server} prompts`)
              return { title: `Raven MCP: ${args.server}`, output: formatMcpList(`Prompts for ${args.server}`, prompts) }
            }

            if (operation === "get_prompt") {
              if (!args.name) return { title: `Raven MCP: ${args.server}`, output: "get_prompt requires name." }
              const result = await withTimeout(client.getPrompt({ name: args.name, arguments: parseMcpArguments(args.argumentsJson) }), timeout, `Getting ${args.server} prompt`)
              return { title: `Raven MCP: ${args.server}.${args.name}`, output: formatMcpResult(result) }
            }

            return { title: `Raven MCP: ${args.server}`, output: `Unsupported operation: ${operation}` }
          } catch (err: any) {
            return { title: `Raven MCP: ${args.server}`, output: `MCP call failed: ${err?.message ?? err}` }
          }
        },
      }),
    },

    // Track agent ↔ session mapping for allowlist + Raven exclusion
    "chat.message"(input: any, _output: any) {
      if (input.agent) {
        sessionAgents.set(input.sessionID, input.agent)
        if (input.agent === "raven") {
          ravenSessions.add(input.sessionID)
        }
      }
    },

    event(input: { event: any }) {
      // Track subagent session → parent mapping for accurate context counting
      const evt = input.event
      if (evt?.type === "session.created" && evt?.properties?.parentID) {
        ravenSessionParents.set(evt.properties.parentID, evt.properties.id)
      }

      if (!updateToastPending) return
      updateToastPending = false
      setTimeout(() => void notifyIfUpdateAvailable(), 500)
      scheduleOnDemandMcpRefresh()
    },

    // /raven on|off|route|mcp|model <name>|effort <value>|timeout <seconds>|stats|status
    async "command.execute.before"(input: any, output: any) {
      if (input.command !== "raven") return
      output.parts.length = 0
      const raw = input.arguments.trim()
      const arg = raw.toLowerCase()

      if (arg === "on") {
        config.enabled = true
        saveConfig(config)
        output.parts.push({ type: "text", text: "Raven tool/MCP routing enabled. Non-Raven agents will be redirected to raven_seek for configured tools." })
      } else if (arg === "off") {
        config.enabled = false
        saveConfig(config)
        output.parts.push({ type: "text", text: "Raven tool/MCP routing disabled. All agents can use tools directly." })
      } else if (arg === "stats") {
        output.parts.push({ type: "text", text: statsText() })
      } else if (arg === "route") {
        output.parts.push({ type: "text", text: `${routeSummary()}\n\nUsage:\n  /raven route tool add <tool_name>\n  /raven route tool remove <tool_name>\n  /raven route mcp add <server_name>\n  /raven route mcp remove <server_name>\n  /raven route keyword add <keyword>\n  /raven route keyword remove <keyword>` })
      } else if (arg.startsWith("route ")) {
        const parts = raw.split(/\s+/)
        const kind = parts[1]?.toLowerCase()
        const action = parts[2]?.toLowerCase()
        const name = parts.slice(3).join(" ").trim()
        const key = kind === "tool" ? "routeTools" : kind === "mcp" || kind === "server" ? "routeMcpServers" : kind === "keyword" ? "routeToolKeywords" : undefined

        if (!key || !["add", "remove", "rm"].includes(action) || !name) {
          output.parts.push({ type: "text", text: "Usage:\n  /raven route tool add <tool_name>\n  /raven route tool remove <tool_name>\n  /raven route mcp add <server_name>\n  /raven route mcp remove <server_name>\n  /raven route keyword add <keyword>\n  /raven route keyword remove <keyword>" })
        } else {
          const values = uniqueStrings(config[key])
          const exists = values.some((value) => value.toLowerCase() === name.toLowerCase())
          config[key] = action === "add"
            ? exists ? values : [...values, name]
            : values.filter((value) => value.toLowerCase() !== name.toLowerCase())
          saveConfig(config)
          output.parts.push({ type: "text", text: routeSummary() })
        }
      } else if (arg === "mcp") {
        output.parts.push({ type: "text", text: `${onDemandMcpStatus()}\n\nUsage:\n  /raven mcp refresh [server_name]\n  /raven mcp detail full\n  /raven mcp detail minimized` })
      } else if (arg.startsWith("mcp ")) {
        const parts = raw.split(/\s+/)
        const action = parts[1]?.toLowerCase()
        if (action === "refresh") {
          const serverName = parts.slice(2).join(" ").trim() || undefined
          const result = await refreshOnDemandMcpDescriptions(true, serverName)
          output.parts.push({
            type: "text",
            text: `On-demand MCP refresh complete.\n  Refreshed: ${result.refreshed.length ? result.refreshed.join(", ") : "none"}\n  Failed: ${result.failed.length ? result.failed.join(", ") : "none"}`,
          })
        } else if (action === "detail") {
          const detail = parts[2]?.toLowerCase()
          if (detail !== "full" && detail !== "minimized") {
            output.parts.push({ type: "text", text: `Usage: /raven mcp detail full|minimized\nCurrent: ${config.onDemandMcpDescriptionDetail ?? "full"}` })
          } else {
            config.onDemandMcpDescriptionDetail = detail
            saveConfig(config)
            output.parts.push({ type: "text", text: `On-demand MCP guidance detail set to: ${detail}\nRestart opencode for startup instructions/tool descriptions to fully refresh.` })
          }
        } else {
          output.parts.push({ type: "text", text: "Usage:\n  /raven mcp\n  /raven mcp refresh [server_name]\n  /raven mcp detail full\n  /raven mcp detail minimized" })
        }
      } else if (arg === "update") {
        try {
          const info = await refreshUpdateInfo()
          if (!info.latest) {
            output.parts.push({ type: "text", text: `Could not check npm for ${PACKAGE_NAME}. Try again later.\n\n${manualUpdateText()}` })
          } else if (!info.available) {
            output.parts.push({ type: "text", text: `Raven is up to date (${info.current}). Latest on npm: ${info.latest}.` })
          } else {
            const removed = clearPluginCache()
            output.parts.push({ type: "text", text: `Raven update available: ${info.current} → ${info.latest}.\n\nCleared ${removed.length} opencode plugin cache entr${removed.length === 1 ? "y" : "ies"}. ${manualUpdateText(info.latest)}` })
          }
        } catch (err: any) {
          output.parts.push({ type: "text", text: `Raven update check failed: ${err?.message ?? err}\n\n${manualUpdateText()}` })
        }
      } else if (arg.startsWith("model ")) {
        const model = raw.slice(6).trim()
        if (!model) {
          output.parts.push({ type: "text", text: `Usage: /raven model <name>\nCurrent model: ${config.model || fm.model || "(default)"}` })
        } else {
          config.model = model
          saveConfig(config)
          output.parts.push({ type: "text", text: `Raven model set to: ${model}\nRestart opencode for the change to take effect.` })
        }
      } else if (arg.startsWith("effort ")) {
        const effort = raw.slice(7).trim()
        if (!effort) {
          output.parts.push({ type: "text", text: `Usage: /raven effort <value>\nCurrent: ${config.reasoning_effort || fm.reasoning_effort || "(default)"}` })
        } else {
          config.reasoning_effort = effort
          saveConfig(config)
          output.parts.push({ type: "text", text: `Raven reasoning effort set to: ${effort}\nRestart opencode for the change to take effect.` })
        }
      } else if (arg.startsWith("timeout ")) {
        const secs = parseInt(raw.slice(8).trim(), 10)
        if (!secs || secs < 10) {
          output.parts.push({ type: "text", text: `Usage: /raven timeout <seconds>\nMust be at least 10. Current: ${config.timeout ?? 180}s` })
        } else {
          config.timeout = secs
          saveConfig(config)
          output.parts.push({ type: "text", text: `Raven timeout set to ${secs}s. Takes effect immediately.` })
        }
      } else {
        const enabled = config.enabled ? "enabled" : "disabled"
        const model = config.model || fm.model || "(default)"
        const effort = config.reasoning_effort || fm.reasoning_effort || "(default)"
        const timeout = config.timeout ?? 180
        let update = "Update: unable to check npm."
        try {
          const info = await getUpdateInfo()
          update = info.available && info.latest
            ? `Update: ${info.latest} available. Run /raven update, then restart opencode.`
            : `Update: up to date${info.latest ? ` (latest ${info.latest})` : ""}.`
        } catch { /* keep fallback */ }
        output.parts.push({ type: "text", text: `Raven is ${enabled}. Version: ${PACKAGE_VERSION}. Model: ${model}. Reasoning: ${effort}. Timeout: ${timeout}s\n${update}\n\n${routeSummary()}\n\n${mcpSummary()}\n\n${statsText()}\n\nCommands:\n  /raven on      — enable tool/MCP routing\n  /raven off     — disable tool/MCP routing\n  /raven route   — show or edit routed tools/MCP servers/keywords\n  /raven mcp     — show or refresh on-demand MCP metadata\n  /raven update  — check npm, clear plugin cache if newer, then restart opencode\n  /raven model <name> — change Raven's model (requires restart)\n  /raven effort <value> — change Raven's reasoning effort (requires restart)\n  /raven timeout <seconds> — change raven_seek timeout\n  /raven stats   — show context saved` })
      }
    },

    "tool.execute.before"(input: any, output: any) {
      if (input.tool === "raven_seek" && (ravenSessions.has(input.sessionID) || sessionAgents.get(input.sessionID) === "raven")) {
        throw new Error("raven_seek is disabled inside Raven. Use Raven's direct search/fetch tools instead.")
      }

      if (input.tool === "raven_mcp" && !ravenSessions.has(input.sessionID) && sessionAgents.get(input.sessionID) !== "raven") {
        throw new Error("raven_mcp is only available inside Raven. Use raven_seek(query=\"Use the relevant on-demand MCP to handle this request\") instead.")
      }

      if (!config.enabled) return
      if (ravenSessions.has(input.sessionID)) return
      if (isExcluded(sessionAgents.get(input.sessionID))) return
      if (config.excludeTools?.some((name) => name.toLowerCase() === input.tool.toLowerCase())) return

      // ── Subagent prompt injection: inject Raven guidance into every subagent ──
      if ((input.tool === "task" || input.tool === "subtask") && output.args) {
        const subagentType = input.tool === "task" ? (output.args.subagent_type ?? "") : ""
        if (subagentType === "raven") {
          ravenTaskCalls.add(input.callID)
        }
        if (subagentType !== "raven" && !isExcluded(subagentType)) {
          const field = ["prompt", "description", "request", "objective", "query"].find(
            (f) => f in output.args
          ) ?? "prompt"
          output.args[field] = `${output.args[field] ?? ""}\n\n<raven_guidance>\n${ravenGuidance()}\n</raven_guidance>`
        }
      }

      // ── Block routed tools/MCPs for non-Raven agents ──
      const shouldRouteTool = input.tool === "bash" ? false : isRouteConfigured(input.tool)
      const isSearchBashCmd = isRouteConfigured("bash") && isSearchBash(input.tool, output.args || input.args)

      if (shouldRouteTool || isSearchBashCmd) {
        const args = compactArgs(output.args || input.args)
        if (output.args && typeof output.args === "object") output.args = args
        throw new Error(rerouteMessage(input.tool, args))
      }
    },

    "tool.execute.after"(input: any, output: any) {
      if (ravenTaskCalls.has(input.callID)) {
        ravenTaskCalls.delete(input.callID)
        // Try task metadata first (built-in tools preserve metadata)
        const ravenSessionId = output.metadata?.sessionId ?? ravenSessionParents.get(input.sessionID)
        if (ravenSessionId) {
          if (ravenSessionParents.has(input.sessionID)) ravenSessionParents.delete(input.sessionID)
          void countRavenSavedCandidateBytes(ravenSessionId)
            .then((total) => {
              const saved = Math.max(0, total - String(output.output ?? "").length)
              if (saved > 0) addBytes(saved)
            })
            .catch(() => {
              // Without token metadata we cannot separate saved context from the compact answer.
            })
        }
      }
    },
  }
}) satisfies Plugin
